### ISSUE TITLE
Unused parameter declerations

### ISSUE THREAD

**Issue by KaraMelih** [XENONnT/fuse#128]
https://github.com/XENONnT/fuse/blob/0c7736a8c28325860a5d28044fe34892fc8bacbd/fuse/plugins/micro_physics/yields.py#L404-L467

In these functions, the parameter dictionaries are passed but most of them are not used (also not used `g` and `PenningQuenching`), and rather hard-coded values are used. Not sure if this is intentional, if so, please resolve the issue as solved.

**Comment by HenningSE** [comment]
Hi @KaraMelih , yes you are totally right this part of the code is not really nice. It is basically a copy of the code in epix and it was never polished for fuse. The reason is that it is not used as default and my main motivation in putting it there was to demonstrate how one could change e.g. the yield calculation in fuse by exchanging plugins. 

If you need this code, we can clean it up a bit and make it ready for use again.

**Comment by KaraMelih** [comment]
Thanks for the quick response! No, actually I do not need it particularly. While, going through the scripts my IDE highlighted these parts, and I wanted to open an issue to see if this was intentional or an oversight. 

All good then! I'm closing the issue. <3
